name: Rebuild auto updating images

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  release-a-library:
    name: Update release-a-library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash release-a-library/build-and-push.bash

  x86-64-unknown-linux-builder:
    name: Update x86-64-unknown-linux-builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder/build-and-push.bash

  x86-64-unknown-linux-builder-with-libressl_3_1_2:
    name: Update x86-64-unknown-linux-builder-with-libressl-3.1.2
    runs-on: ubuntu-latest
    needs: [x86-64-unknown-linux-builder]
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-libressl-3.1.2/build-and-push.bash

  x86-64-unknown-linux-builder-with-openssl_1_1_1g:
    name: Update x86-64-unknown-linux-builder-with-openssl_1.1.1g
    runs-on: ubuntu-latest
    needs: [x86-64-unknown-linux-builder]
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-openssl_1.1.1g/build-and-push.bash

  x86-64-unknown-linux-builder-with-pcre:
    name: Update x86-64-unknown-linux-builder-with-pcre
    runs-on: ubuntu-latest
    needs: [x86-64-unknown-linux-builder]
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-pcre/build-and-push.bash
