name: Rebuild linux builder images

on:
  repository_dispatch:
    types: [ponyc-musl-nightly-released]

jobs:
  x86-64-unknown-linux-builder:
    name: Update x86-64-unknown-linux-builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder/build-and-push.bash

  x86-64-unknown-linux-builder-with-libressl_3_1_2:
    name: Update x86-64-unknown-linux-builder-with-libressl-3.1.2
    runs-on: ubuntu-latest
    needs: [x86-64-unknown-linux-builder]
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-libressl-3.1.2/build-and-push.bash

  x86-64-unknown-linux-builder-with-openssl_1_1_1g:
    name: Update x86-64-unknown-linux-builder-with-openssl_1.1.1g
    runs-on: ubuntu-latest
    needs: [x86-64-unknown-linux-builder]
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-openssl_1.1.1g/build-and-push.bash

  x86-64-unknown-linux-builder-with-pcre:
    name: Update x86-64-unknown-linux-builder-with-pcre
    runs-on: ubuntu-latest
    needs: [x86-64-unknown-linux-builder]
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-pcre/build-and-push.bash

  send-linux-builders-updated-event:
    needs: [x86-64-unknown-linux-builder, x86-64-unknown-linux-builder-with-libressl_3_1_2, x86-64-unknown-linux-builder-with-openssl_1_1_1g, x86-64-unknown-linux-builder-with-pcre]

    name: Send nightly release event
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - ponylang/appdirs
          - ponylang/changelog-tool
          - ponylang/http_server
          - ponylang/ponyup
          - ponylang/valbytes
    steps:
      - name: Send
        uses: ponylang-main/repository-dispatch@ce5485de42c9b2622d2ed064be479e8ed65e76f4
        with:
          token: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: shared-docker-linux-builders-updated
          client-payload: '{}'
