name: Rebuild linux builder images

on:
  repository_dispatch:
    types:
      - ponyc-musl-nightly-released
      - ponyc-musl-released

jobs:
  x86-64-unknown-linux-builder:
    name: Update x86-64-unknown-linux-builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder/build-and-push.bash
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  x86-64-unknown-linux-builder-with-libressl_3_7_2:
    needs:
      - x86-64-unknown-linux-builder

    name: Update x86-64-unknown-linux-builder-with-libressl-3.7.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-libressl-3.7.2/build-and-push.bash
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  x86-64-unknown-linux-builder-with-libressl_3_7_3:
    needs:
      - x86-64-unknown-linux-builder

    name: Update x86-64-unknown-linux-builder-with-libressl-3.7.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-libressl-3.7.3/build-and-push.bash
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  x86-64-unknown-linux-builder-with-openssl_1_1_1t:
    needs:
      - x86-64-unknown-linux-builder

    name: Update x86-64-unknown-linux-builder-with-openssl_1.1.1t
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-openssl_1.1.1t/build-and-push.bash
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  x86-64-unknown-linux-builder-with-openssl_1_1_1w:
    needs:
      - x86-64-unknown-linux-builder

    name: Update x86-64-unknown-linux-builder-with-openssl_1.1.1w
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-openssl_1.1.1w/build-and-push.bash
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  x86-64-unknown-linux-builder-with-openssl_3_1_0:
    needs:
      - x86-64-unknown-linux-builder

    name: Update x86-64-unknown-linux-builder-with-openssl_3.1.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-openssl_3.1.0/build-and-push.bash
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  x86-64-unknown-linux-builder-with-openssl_3_1_3:
    needs:
      - x86-64-unknown-linux-builder

    name: Update x86-64-unknown-linux-builder-with-openssl_3.1.3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-openssl_3.1.3/build-and-push.bash
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  x86-64-unknown-linux-builder-with-openssl_3_2_0:
    needs:
      - x86-64-unknown-linux-builder

    name: Update x86-64-unknown-linux-builder-with-openssl_3.2.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-openssl_3.2.0/build-and-push.bash
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  x86-64-unknown-linux-builder-with-pcre:
    needs:
      - x86-64-unknown-linux-builder

    name: Update x86-64-unknown-linux-builder-with-pcre
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        # v2.2.0
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: bash x86-64-unknown-linux-builder-with-pcre/build-and-push.bash
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  send-linux-builders-updated-event:
    needs:
      - x86-64-unknown-linux-builder
      - x86-64-unknown-linux-builder-with-libressl_3_7_2
      - x86-64-unknown-linux-builder-with-libressl_3_7_3
      - x86-64-unknown-linux-builder-with-openssl_1_1_1t
      - x86-64-unknown-linux-builder-with-openssl_1_1_1w
      - x86-64-unknown-linux-builder-with-openssl_3_1_0
      - x86-64-unknown-linux-builder-with-openssl_3_1_3
      - x86-64-unknown-linux-builder-with-openssl_3_2_0
      - x86-64-unknown-linux-builder-with-pcre

    name: Send 'shared-docker-linux-builders-updated' event
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo:
          - ergl/pony-protobuf
          - ponylang/appdirs
          - ponylang/changelog-tool
          - ponylang/corral
          - ponylang/crypto
          - ponylang/fork_join
          - ponylang/github_rest_api
          - ponylang/glob
          - ponylang/http
          - ponylang/http_server
          - ponylang/json
          - ponylang/logger
          - ponylang/lori
          - ponylang/net_ssl
          - ponylang/peg
          - ponylang/pony-sync-helper
          - ponylang/ponydoc
          - ponylang/ponyup
          - ponylang/postgres
          - ponylang/reactive_streams
          - ponylang/regex
          - ponylang/rfc-tool
          - ponylang/semver
          - ponylang/templates
          - ponylang/valbytes
          - seantallen-org/msgpack
    steps:
      - name: Send
        # v2.1.1
        uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588
        with:
          token: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: shared-docker-linux-builders-updated
          client-payload: '{}'
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.

  prune-untagged-builder-images:
    needs:
      - send-linux-builders-updated-event

    name: Prune untagged builder images
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - shared-docker-ci-x86-64-unknown-linux-builder
          - shared-docker-ci-x86-64-unknown-linux-builder-with-libressl-3.7.2
          - shared-docker-ci-x86-64-unknown-linux-builder-with-libressl-3.7.3
          - shared-docker-ci-x86-64-unknown-linux-builder-with-openssl_1.1.1t
          - shared-docker-ci-x86-64-unknown-linux-builder-with-openssl_1.1.1w
          - shared-docker-ci-x86-64-unknown-linux-builder-with-openssl_3.1.0
          - shared-docker-ci-x86-64-unknown-linux-builder-with-openssl_3.1.3
          - shared-docker-ci-x86-64-unknown-linux-builder-with-openssl_3.2.0
          - shared-docker-ci-x86-64-unknown-linux-builder-with-pcre

    steps:
      - name: Prune
        # v4.1.1
        uses: actions/delete-package-versions@0d39a63126868f5eefaa47169615edd3c0f61e20
        with:
          package-name: ${{ matrix.image }}
          package-type: 'container'
          min-versions-to-keep: 1
          delete-only-untagged-versions: 'true'
      - name: Send alert on failure
        if: ${{ failure() }}
        uses: zulip/github-actions-zulip/send-message@b62d5a0e48a4d984ea4fce5dd65ba691963d4db4
        with:
          api-key: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_API_KEY }}
          email: ${{ secrets.ZULIP_SCHEDULED_JOB_FAILURE_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ github.repository }} scheduled job failure
          content: ${{ github.server_url}}/${{ github.repository }}/actions/runs/${{ github.run_id }} failed.
