name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  superlinter:
    name: Lint bash, docker, markdown, and yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_MD: true
          VALIDATE_YAML: true

  validate-actionlint-image-builds:
    name: Validate release Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=actionlint/Dockerfile ."

  validate-emacs-mode-release-image-builds:
    name: Validate release Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=emacs-mode-release/Dockerfile ."

  validate-release-a-library-image-builds:
    name: Validate release-a-library Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=release-a-library/Dockerfile ."

  validate-x86-64-unknown-linux-builder-image-builds:
    name: Validate x86-64-unknown-linux-builder Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-libressl-3_7_2-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-libressl-3.7.2 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-libressl-3.7.2/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-libressl-3_7_3-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-libressl-3.7.3 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-libressl-3.7.3/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-openssl_1_1_1t-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-openssl_1.1.1t Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-openssl_1.1.1t/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-openssl_1_1_1w-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-openssl_1.1.1w Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-openssl_1.1.1w/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-openssl_3_1_0-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-openssl_3.1.0 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-openssl_3.1.0/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-openssl_3_1_3-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-openssl_3.1.3 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-openssl_3.1.3/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-openssl_3_2_0-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-openssl_3.2.0 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-openssl_3.2.0/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-pcre-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-pcre Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-pcre/Dockerfile ."
