name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  superlinter:
    name: Lint bash, docker, markdown, and yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_MD: true
          VALIDATE_YAML: true
          VALIDATE_R: false

  validate-actionlint-image-builds:
    name: Validate actionlint Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=actionlint/Dockerfile ."

  validate-emacs-mode-release-image-builds:
    name: Validate emacs-mode release Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=emacs-mode-release/Dockerfile ."

  validate-release-a-library-image-builds:
    name: Validate release-a-library Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=release-a-library/Dockerfile ."

  validate-x86-64-unknown-linux-builder-image-builds:
    name: Validate x86-64-unknown-linux-builder Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-libressl-3_9_1-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-libressl-3.9.1 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-libressl-3.9.1/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-libressl-3_9_2-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-libressl-3.9.2 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-libressl-3.9.2/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-libressl-4_0_0-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-libressl-4.0.0 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-libressl-4.0.0/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-openssl_1_1_1w-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-openssl_1.1.1w Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-openssl_1.1.1w/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-openssl_3_3_0-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-openssl_3.3.0 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-openssl_3.3.0/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-openssl_3_3_2-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-openssl_3.3.2 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-openssl_3.3.2/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-pcre-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-pcre Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-pcre/Dockerfile ."
