name: PR

on: pull_request

jobs:
  superlinter:
    name: Lint bash, docker, markdown, and yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_MD: true
          VALIDATE_YAML: true

  validate-release-image-builds:
    name: Validate release Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull --file=release/Dockerfile ."

  validate-release-a-library-image-builds:
    name: Validate release-a-library Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull --file=release-a-library/Dockerfile ."

  validate-x86-64-unknown-linux-builder-image-builds:
    name: Validate x86-64-unknown-linux-builder Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-libressl-3_5_2-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-libressl-3.5.2 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-libressl-3.5.2/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-libressl-3_5_3-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-libressl-3.5.3 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-libressl-3.5.3/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-openssl_1_1_1n-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-openssl_1.1.1n Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-openssl_1.1.1n/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-openssl_1_1_1q-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-openssl_1.1.1q Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-openssl_1.1.1q/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-pcre-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-pcre Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-pcre/Dockerfile ."
