name: PR

on: pull_request

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  superlinter:
    name: Lint bash, docker, markdown, and yaml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Lint codebase
        uses: docker://github/super-linter:v3.8.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_BASH: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_MD: true
          VALIDATE_YAML: true

  validate-actionlint-image-builds:
    name: Validate actionlint Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=actionlint/Dockerfile ."

  validate-emacs-mode-release-image-builds:
    name: Validate emacs-mode release Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=emacs-mode-release/Dockerfile ."

  validate-release-a-library-image-builds:
    name: Validate release-a-library Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=release-a-library/Dockerfile ."

  validate-x86-64-unknown-linux-builder-image-builds:
    name: Validate x86-64-unknown-linux-builder Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder/Dockerfile ."

  validate-arm64-unknown-linux-builder-image-builds:
    name: Validate arm64-unknown-linux-builder Docker image builds
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up Docker Buildx
        # v3.10.0
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
      - run: docker buildx version
      - name: Docker build
        run: "docker buildx build --platform linux/arm64 --pull --file=arm64-unknown-linux-builder/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-libressl-3_9_2-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-libressl-3.9.2 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-libressl-3.9.2/Dockerfile ."

  validate-arm64-unknown-linux-builder-with-libressl-4_0_0-image-builds:
    name: Validate arm64-unknown-linux-builder-with-libressl-4.0.0 Docker image builds
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up Docker Buildx
        # v3.10.0
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
      - run: docker buildx version
      - name: Docker build
        run: "docker buildx build --platform linux/arm64 --pull --file=arm64-unknown-linux-builder-with-libressl-4.0.0/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-libressl-4_0_0-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-libressl-4.0.0 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-libressl-4.0.0/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-openssl_1_1_1w-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-openssl_1.1.1w Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-openssl_1.1.1w/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-openssl_3_3_2-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-openssl_3.3.2 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-openssl_3.3.2/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-openssl_3_4_1-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-openssl_3.4.1 Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-openssl_3.4.1/Dockerfile ."

  validate-x86-64-unknown-linux-builder-with-pcre-image-builds:
    name: Validate x86-64-unknown-linux-builder-with-pcre Docker image builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Docker build
        run: "docker build --pull --file=x86-64-unknown-linux-builder-with-pcre/Dockerfile ."

  validate-standard-builder-builds:
    name: Validate standard builder image builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up buildx
        # v3.10.0
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
      - name: Test build
        run: "docker buildx build --platform linux/arm64,linux/amd64 --pull --file=standard-builder/Dockerfile ."

  validate-standard-builder-with-libressl-4_2_0-builds:
    name: Validate standard builder with libressl 4.2.0 image builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up buildx
        # v3.10.0
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
      - name: Test build
        run: "docker buildx build --platform linux/arm64,linux/amd64 --pull --file=standard-builder-with-libressl-4.2.0/Dockerfile ."
